name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    if: ${{ !github.event.repository.is_template }}
    uses: opencoreemr/github-workflows-public/.github/workflows/release-please-reusable.yml@1.0.0
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
